version: '3'

services:
    db:
        build: ./mysql
        container_name: db
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=nodedb

    service:
        build: ./service
        container_name: service
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
        command: ["node", "index.js"]
        depends_on: 
            - db

    nginx:
        build: ./nginx
        container_name: nginx
        entrypoint: dockerize -wait tcp://service:3000 -timeout 20s
        command: ["nginx", "-g", "daemon off;"]
        ports: 
            - 8080:80
        depends_on: 
            - service